@Host= http://localhost:5105

###========================================================= AuditLog
###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - List
GET {{Host}}/api/auditlogs

###============================================================= User
###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - List
GET {{Host}}/api/users/list

###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Create
# @name UserCreate
POST {{Host}}/api/users/create
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe"
}

###============================================================= Cart
###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - List
GET {{Host}}/api/carts/list

###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Create
POST {{Host}}/api/carts/create
Authorization: Bearer {{UserCreate.response.body.message}}


###========================================================== Product
###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - List
GET {{Host}}/api/products/list

###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Create
# @name ProductCreate
POST {{Host}}/api/products/create
Content-Type: application/json
Authorization: Bearer {{UserCreate.response.body.message}}

{
  "name": "iPhone 15 Pro",
  "price": 39900
}

###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Update
PUT {{Host}}/api/products/update/{{ProductCreate.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{UserCreate.response.body.message}}

{
  "name": "iPhone 15 Pro Max",
  "price": 99999
}

###- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Delete
DELETE {{Host}}/api/products/delete/{{ProductCreate.response.body.id}}
Authorization: Bearer {{UserCreate.response.body.message}}

###

GET {{Host}}/api/tokens/CheckAuth
Authorization: Bearer {{UserCreate.response.body.message}}